name: toplu-islem-otomatik

on:
  workflow_dispatch:  # Manuel tetikleme için (opsiyonel)
  schedule:
    - cron: '0 0 * * *'  # Günlük otomatik çalıştırma (opsiyonel)

jobs:
  reorder:
    runs-on: ubuntu-latest

    steps:
      # Kaynak kodu çek
      - uses: actions/checkout@v4

      # Python kurulumu
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Chromium + ChromeDriver kurulumu
      - name: Install Chrome & driver
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo ln -sf /usr/bin/chromium-browser /usr/bin/google-chrome
          sudo ln -sf /usr/bin/chromedriver /usr/local/bin/chromedriver

      # Bağımlılıkları yükle
      - name: Install deps
        run: pip install selenium

      # Sabit bir `batch` değeriyle çalıştır
      - name: Run batch script
        run: |
          python toplu-islem.py --batch "231321:2,235412:5"  # Örnek sabit değer
